config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'cars#index'

  resources :cars
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  before_save :titleize_manufacturer_name
  belongs_to :user

  private

  def titleize_manufacturer_name
    self.manufacturer = manufacturer.titleize
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :cars

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :registerable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = current_user.cars
  end

  def new
    @car = current_user.cars.new
  end

  def show
    @car = Car.find(params[:id])
  end

  def create
    @car = current_user.cars.create(car_params)
    if @car.save
      flash[:success] = "New car added successfully"
      redirect_to cars_path
    else
      render 'new'
    end
  end

  def destroy
    Car.find(params[:id]).destroy
    flash[:success] = "Your car removed!"
    redirect_to cars_path
  end

  private

  def car_params
    params.require(:car).permit(:custom_name, :manufacturer, :model, :production_year, :trim)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns full title on a per-page basis
  def full_title(page_title='')
    base_title = "Carator"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/controller_helper.rb
module ControllerHelper
  def log_in(user)
    warden = request.env["warden"]

    allow(warden).to receive(:authenticate!).and_return(user)
    allow(controller).to receive(:current_user).and_return(user)
  end
end

app/views/cars/_car.html.haml
%li.car-row
  .jumbotron
    %h2
      = link_to "#{car.custom_name}", car, class: "car-link"
    %h3
      = link_to "#{car.manufacturer} #{car.model} #{car.trim}", car, class: "car-link"

app/views/cars/_error_messages.html.haml
- if @car.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains #{pluralize(@car.errors.count, "error")}.
    %ul
      - @car.errors.full_messages.each do |msg|
        %li= msg

app/views/cars/_form.html.haml
:javascript
  $(document).on('turbolinks:load', function () {
      $.getScript("http://www.carqueryapi.com/js/carquery.0.3.4.js", function () {
          let carquery = new CarQuery();
          carquery.init();
          carquery.initYearMakeModelTrim('car_production_year', 'car_manufacturer', 'car_model', 'car_trim');
      });
  });
.row
  .col-md-6.col-md-offset-3
    = form_for @car, url: {action: "create"} do |car_form|
      = car_form.text_field :custom_name, :placeholder => t('car_name_hint')
      = car_form.select(:production_year, options_for_select([], 0))
      = car_form.select(:manufacturer, options_for_select([], 0))
      = car_form.select(:model, options_for_select([], 0))
      = car_form.select(:trim, options_for_select([], 0))
      = car_form.submit yield(:button_text)

app/views/cars/index.html.haml
- provide(:title, t('my_cars'))
- provide(:adding_button_text, t('add_new_car'))
%ul.list-unstyled
  = link_to yield(:adding_button_text), new_car_path, class: 'btn btn-primary'
  = render @cars

app/views/cars/new.html.haml
- provide(:button_text, t('add_new_car'))
- provide(:title, t('add_new_car'))
= render 'form'

app/views/cars/show.html.haml
- provide(:title, @car.custom_name)
- provide(:remove_car_btn_text, t('remove_car_title'))
- provide(:remove_confirmation_msg_text, t('remove_car_confirmation'))
.container
  .col-xs-8.col-xs-offset-2
    .jumbotron.text-center
      .h1
        = @car.custom_name
      .h3
        = @car.manufacturer
      .h3
        = @car.model
      .p
        = @car.trim

      = link_to(yield(:remove_car_btn_text),
                @car,
                method: :delete,
                class: 'btn btn-danger',
                data: { confirm: yield(:remove_confirmation_msg_text) })

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse
  .container
    .navbar-header
      %a.navbar-brand{:href => "#"} Carator
    #navbar-collapse-4.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            = link_to t('my_cars'), cars_path
          %li
            = link_to t('log_out'), destroy_user_session_path, method: :delete
        - else
          %li
            = link_to t('log_in'), new_user_session_path
    / /.navbar-collapse
  / /.container
/ /.navbar

app/views/layouts/_rails_defaults.html.haml
= csrf_meta_tags
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= full_title(yield(:title))
    = render 'layouts/rails_defaults'
  %body
    = render 'layouts/header'
    %p.notice= notice
    %p.alert= alert
    = yield